

### Peliculas populares
GET http://localhost:5500/movies/populars HTTP/1.1

### Peliculas en cartelera
GET http://localhost:5500/movies/now-playing HTTP/1.1

### Proximas peliculas
GET http://localhost:5500/movies/upcoming HTTP/1.1

### Peliculas animadas
GET http://localhost:5500/movies/animation HTTP/1.1

### Tendencias
GET http://localhost:5500/movies/trending HTTP/1.1

### Encontrar pelicula por id
GET http://localhost:5500/movies/634649 HTTP/1.1

### Encontrar pelicula por busqueda
GET http://localhost:5500/movies/search?query=spiderman&page=2 HTTP/1.1

### Series populares
GET http://localhost:5500/series/populars HTTP/1.1

### Series al aire
GET http://localhost:5500/series/on-the-air HTTP/1.1

### Lista de generos de series
GET http://localhost:5500/series/genres HTTP/1.1

### Encontrar serie por busqueda
GET http://localhost:5500/series/search?query=spiderman HTTP/1.1




### Crear usuario
POST http://localhost:5500/users HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "balta",
    "email": "aa@gmail.com",
    "image": "...",
    "password": "123"
}

### Crear favorito
POST http://localhost:5500/favorites HTTP/1.1
content-type: application/json

{
    "id": 2,
    "favId": 82452,
    "type": "series",
    "userId": 1
}



### Acceder a todos los usuarios
GET  http://localhost:5500/users/all HTTP/1.1

### Acceder a usuario por id
GET  http://localhost:5500/users/1 HTTP/1.1

### Acceder a favoritos del usuario
GET  http://localhost:5500/favorites/1 HTTP/1.1




### Login usuario
POST http://localhost:5500/users/login HTTP/1.1
content-type: application/json

{
    "email": "aa@gmail.com",
    "password": "123"
}